// Code generated by goctl. DO NOT EDIT.
package types

type GetPhoneReq struct {
	Code string `json:"code"`
}

type WxPhoneBack struct {
	ErrCode   int64     `json:"errcode"`
	ErrMsg    string    `json:"errmsg"`
	PhoneInfo PhoneInfo `json:"phone_info"`
}

type PhoneInfo struct {
	PhoneNumber     string    `json:"phoneNumber"`
	PurePhoneNumber string    `json:"purePhoneNumber"`
	CountryCode     string    `json:"countryCode"`
	WaterMark       WaterMark `json:"watermark"`
}

type WaterMark struct {
	TimeStamp int64  `json:"timestamp"`
	AppId     string `json:"appid"`
}

type GetPhoneResp struct {
	PurePhoneNumber string `json:"purePhoneNumber"`
}

type WxAccessToken struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
}

type Message struct {
	MessageId int64  `json:"messageId,string"`
	FromId    int64  `json:"fromId,string"`
	ToId      int64  `json:"toId,string"`
	Type      int64  `json:"type"`
	Content   string `json:"content"`
	Status    int64  `json:"status"`
	CreatTime string `json:"creatTime"`
}

type GiftContent struct {
	GiftId      int64  `json:"giftId"`
	GiftName    string `json:"giftName"`
	GiftMessage string `json:"giftMessage"`
	GiftAmount  int64  `json:"giftAmount"`
}

type WithDrawContent struct {
	PaymentMethod string `json:"paymentMethod"`
	CurrentStatus string `json:"currentStatus"`
}

type SendPatMessageReq struct {
	FromId int64 `json:"fromId,string"`
	ToId   int64 `json:"toId,string"`
}

type SendPatMessageResp struct {
	Status string `json:"status"`
}

type SendGiftMessageReq struct {
	MerchantId  int64       `json:"merchantId,string"`
	FromId      int64       `json:"fromId,string"`
	ToId        int64       `json:"toId,string"`
	GiftContent GiftContent `json:"giftContent"`
}

type SendGiftMessageResp struct {
	Status string `json:"status"`
}

type GetMessageListReq struct {
	ToId int64 `json:"toId,string"`
	Page int64 `json:"page"`
	Size int64 `json:"size"`
}

type GetMessageListResp struct {
	MessageList []Message `json:"messageList"`
}

type GetHasSendGiftReq struct {
	ToId int64 `json:"toId,string"`
}

type GetHasSendGiftResp struct {
	HasSendGift bool `json:"hasSendGift"`
}

type GetHasNewMessageReq struct {
}

type GetHasNewMessageResp struct {
	HasNewMessage bool  `json:"hasNewMessage"`
	Balance       int64 `json:"balance"`
}

type GetHasNewGiftBCReq struct {
	MerchantId int64 `json:"merchantId,string"`
}

type GetHasNewGiftBCVO struct {
	GiftId   int64  `json:"giftId"`
	FromName string `json:"fromName"`
	ToName   string `json:"toName"`
}

type GetHasNewGiftBCResp struct {
	HasNew              bool                `json:"hasNew"`
	GetHasNewGiftBCList []GetHasNewGiftBCVO `json:"getHasNewGiftBcList"`
}

type User struct {
	UserId        int64    `json:"userId,string"`
	UserName      string   `json:"userName"`
	Avatar        string   `json:"avatar"`
	Balance       int64    `json:"balance"`
	Location      string   `json:"location"`
	Features      []string `json:"features"`
	Mobile        string   `json:"mobile"`
	WechatId      string   `json:"wechatId"`
	Status        int64    `json:"status"`
	LastLoginTime int64    `json:"lastLoginTime"`
	CreatTime     string   `json:"creatTime"`
}

type RegisterReq struct {
	Mobile string `json:"mobile"`
}

type RegisterResp struct {
	UserId      int64             `json:"userId,string"`
	AccessToken GenerateTokenResp `json:"accessToken"`
}

type LoginReq struct {
	Mobile string `json:"mobile"`
}

type LoginResp struct {
	UserId      int64             `json:"userId,string"`
	AccessToken GenerateTokenResp `json:"accessToken"`
}

type GetUserInfoReq struct {
	UserId int64 `json:"userId,string"`
}

type GetUserInfoResp struct {
	User User `json:"user"`
}

type GenerateTokenReq struct {
	UserId int64 `json:"userId,string"`
}

type GenerateTokenResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UpdateUserNameReq struct {
	UserId   int64  `json:"userId,string"`
	UserName string `json:"userName"`
}

type UpdateUserNameResp struct {
	Status string `json:"status"`
}

type UpdateAvatarReq struct {
}

type UpdateAvatarResp struct {
	Avatar string `json:"avatar"`
}

type UpdateFeatureReq struct {
	Features []string `json:"features"`
}

type UpdateFeatureResp struct {
	Status string `json:"status"`
}

type UpdateWechatIdReq struct {
	UserId   int64  `json:"userId,string"`
	WechatId string `json:"wechatId"`
}

type UpdateWechatIdResp struct {
	Status string `json:"status"`
}

type UpdateUserLocationReq struct {
	Location string `json:"location"`
}

type UpdateUserLocationResp struct {
	Status string `json:"status"`
}

type OnlineUsersReq struct {
	MerchantId int64 `json:"merchantId,string"`
}

type OnlineUsersResp struct {
	List []User `json:"list"`
}

type GetUserWechatIdReq struct {
	UserId int64 `json:"userId,string"`
}

type GetUserWechatIdResp struct {
	WechatId string `json:"wechatId"`
}

type GetUserAvatarReq struct {
	File string `path:"file"`
}

type UserToStoreReq struct {
	MerchantId int64 `json:"merchantId,string"`
}

type UserToStoreResp struct {
	Status string `json:"status"`
}

type Location struct {
	AddressName    string `json:"addressName"`
	CityName       string `json:"cityName"`
	ShopName       string `json:"shopName"`
	CustomLocation string `json:"customLocation,omitempty"`
}

type GetSpecialEffectReq struct {
	SpecialEffectId string `path:"specialEffectId"`
}

type Chat struct {
	ChatId    int64  `json:"chatId,string"`
	FromId    int64  `json:"fromId,string"`
	ToId      int64  `json:"toId,string"`
	Content   string `json:"content"`
	Status    int64  `json:"status"`
	CreatTime string `json:"creatTime"`
}

type GetHasNewFriendChatReq struct {
	FromId int64 `json:"fromId,string"`
	ToId   int64 `json:"toId,string"`
}

type GetHasNewFriendChatResp struct {
	HasNew bool `json:"hasNew"`
}

type SendFriendChatReq struct {
	ToId    int64  `json:"toId,string"` // 和用户聊天的那个人
	Content string `json:"content"`
}

type SendFriendChatResp struct {
	Status string `json:"status"`
}

type GetFriendChatListReq struct {
	FromId int64 `json:"fromId,string"` //和用户聊天的那个人
}

type GetFriendChatVO struct {
	FromId    int64  `json:"fromId,string"`
	UserName  string `json:"userName"`
	Avatar    string `json:"avatar"`
	Content   string `json:"content"`
	CreatTime string `json:"creatTime"`
}

type GetFriendChatListResp struct {
	ChatList []GetFriendChatVO `json:"chatList"`
}

type GetUserChatListReq struct {
	Page int64 `json:"page"`
	Size int64 `json:"size"`
}

type GetUserChatVO struct {
	FromId    int64    `json:"fromId,string"`
	UserName  string   `json:"userName"`
	Features  []string `json:"features"`
	Avatar    string   `json:"avatar"`
	Content   string   `json:"content"`
	CreatTime string   `json:"creatTime"`
}

type GetUserChatListResp struct {
	UserChatList []GetUserChatVO `json:"userChatList"`
}

type GetHasNewUserChatReq struct {
}

type GetHasNewUserChatResp struct {
	HasNew bool `json:"hasNew"`
}

type Merchant struct {
	MerchantId   int64    `json:"merchantId,string"`
	MerchantName string   `json:"merchantName"`
	Location     Location `json:"location"`
	Balance      int64    `json:"balance"`
	Status       int64    `json:"status"`
	CreatTime    string   `json:"creatTime"`
}

type Room struct {
	RoomId     int64  `json:"roomId,string"`
	MerchantId int64  `json:"merchantId,string"`
	SerialNum  int64  `json:"serialNum"`
	Status     int64  `json:"status"`
	CreatTime  string `json:"creatTime"`
}

type AddMerchantReq struct {
	MerchantName string   `json:"merchantName"`
	Location     Location `json:"location"`
}

type AddMerchantResp struct {
	Status string `json:"status"`
}

type AddRoomReq struct {
	MerchantId int64 `json:"merchantId,string"`
	SerialNum  int64 `json:"serialNum"`
}

type AddRoomResp struct {
	Status string `json:"status"`
}

type CreatSendGiftOrderReq struct {
	ToId      int64 `json:"toId"`
	GiftPrice int64 `json:"giftPrice"`
}

type CreatSendGiftOrderResp struct {
	OrderSn string `json:"orderSn"`
}

type CreatePaymentReq struct {
	UserId      int64  `json:"userId"`
	PayMode     string `json:"payMode"`
	PayTotal    int64  `json:"payTotal"`
	ServiceType string `json:"serviceType"`
}

type CreatePaymentResp struct {
	Sn string `json:"sn"`
}

type PaymentWxPayReq struct {
	OrderSn     string `json:"orderSn"`
	ServiceType string `json:"serviceType"`
	Code        string `json:"code"`
}

type PaymentWxPayResp struct {
	Appid     string `json:"appid"`
	NonceStr  string `json:"nonceStr"`
	PaySign   string `json:"paySign"`
	Package   string `json:"package"`
	Timestamp string `json:"timestamp"`
	SignType  string `json:"signType"`
}

type ThirdPaymentWxPayReq struct {
	Platform   string  `json:"platform"`
	PayChannel string  `json:"payChannel"`
	SubClass   string  `json:"subClass"`
	TenancyId  string  `json:"tenancyId"`
	StoreId    int64   `json:"storeId"`
	OutTradeNo string  `json:"outTradeNo"`
	Openid     string  `json:"openid"`
	Body       string  `json:"body"`
	Amount     float64 `json:"amount"`
	NotifyUrl  string  `json:"notifyUrl"`
	FusruleId  string  `json:"fusruleId,omitempty"`
}

type JsApiPayConfig struct {
	AppId     string `json:"appId"`
	NonceStr  string `json:"nonceStr"`
	Package   string `json:"package"`
	PaySign   string `json:"paySign"`
	SignType  string `json:"signType"`
	Timestamp string `json:"timestamp"`
}

type PlatformExt struct {
	SxfUuid string `json:"sxfUuid"`
}

type ThirdPaymentWxPayResp struct {
	ErrCode             string         `json:"errCode"`
	ErrMsg              string         `json:"errMsg"`
	JsApiPayConfig      JsApiPayConfig `json:"jsApiPayConfig"`
	OpenId              string         `json:"openId"`
	PaymentProvider     string         `json:"paymentProvider"`
	PaymentProviderName string         `json:"paymentProviderName"`
	PlatformExt         PlatformExt    `json:"platformExt"`
	StoreId             int64          `json:"storeId"`
	TradeRate           float64        `json:"tradeRate"`
	TransactionId       string         `json:"transactionId"`
}

type PaymentWxPayQueryReq struct {
	Sn string `json:"sn"` // 流水单号
}

type PaymentWxPayQueryResp struct {
}

type ThirdPaymentWxPayQueryReq struct {
	Platform      string `json:"platform"`
	PayChannel    string `json:"payChannel"`
	SubClass      string `json:"subClass"`
	TenancyId     string `json:"tenancyId"`
	StoreId       int64  `json:"storeId"`
	TransactionId string `json:"transactionId"`
	OutTradeNo    string `json:"outTradeNo"`
}

type ThirdPaymentWxPayQueryData struct {
	ErrCode             string `json:"errCode"`
	ErrMsg              string `json:"errMsg"`
	StoreId             int64  `json:"storeId"`
	OpenId              string `json:"openId"`
	OutTradeNo          string `json:"outTradeNo"`
	TransactionId       string `json:"transactionId"`
	TradeType           string `json:"tradeType"`
	PaymentProvider     string `json:"paymentProvider"`
	PaymentProviderName string `json:"paymentProviderName"`
	TradeRate           string `json:"tradeRate"`
	TradeState          string `json:"tradeState"`
	Amount              int64  `json:"amount"`
	BuyerPayAmount      int64  `json:"buyerPayAmount"`
	ReceipAmount        string `json:"receipAmount"`
	PlatformExt         string `json:"platformExt"`
}

type ThirdPaymentWxPayQueryResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}

type PaymentWxPayCallbackReq struct {
}

type PaymentWxPayCallbackResp struct {
	ReturnCode string `json:"return_code"`
}

type ThirdPaymentWxPayCallbackReq struct {
	BizCode          string        `json:"bizCode"`
	BizMsg           string        `json:"bizMsg"`
	TimeStamp        string        `json:"timeStamp"`
	Sign             string        `json:"sign"`
	Mno              string        `json:"mno"`
	OrdNo            string        `json:"ordNo"`
	Uuid             string        `json:"uuid"`
	PayTime          string        `json:"payTime"`
	Amt              string        `json:"amt"`
	PayType          string        `json:"payType"`
	PayWay           string        `json:"payWay"`
	YlTrmNo          string        `json:"ylTrmNo,omitempty"`
	OrigOrdNo        string        `json:"origOrdNo,omitempty"`
	OrigUuid         string        `json:"origUuid,omitempty"`
	Scene            string        `json:"scene,omitempty"`
	BuyerId          string        `json:"buyerId,omitempty"`
	BuyerAccount     string        `json:"buyerAccount,omitempty"`
	TransactionId    string        `json:"transactionId,omitempty"`
	DyType           string        `json:"dyType,omitempty"`
	TotalOffstAmt    string        `json:"totalOffstAmt,omitempty"`
	SettleAmt        string        `json:"settleAmt"`
	PayBank          string        `json:"payBank,omitempty"`
	PointAmount      string        `json:"pointAmount,omitempty"`
	RecFeeRate       string        `json:"recFeeRate,omitempty"`
	RecFeeAmt        string        `json:"recFeeAmt,omitempty"`
	RealRefundAmount string        `json:"realRefundAmount,omitempty"`
	ChannelId        string        `json:"channelId,omitempty"`
	SubMechId        string        `json:"subMechId,omitempty"`
	RefBuyerAmt      string        `json:"refBuyerAmt,omitempty"`
	OpenId           string        `json:"openId,omitempty"`
	ActivityNo       string        `json:"activityNo，omitempty"`
	SxfUuid          string        `json:"sxfUuid"`
	Extend           string        `json:"extend,omitempty"`
	Promotion        []interface{} `json:"promotion,omitempty"`
	Detail           string        `json:"detail,omitempty"`
	RefundDetail     string        `json:"refundDetail,omitempty"`
	StoreNum         string        `json:"storeNum,omitempty"`
	ClearDt          string        `json:"clearDt,omitempty"`
	FinishTime       string        `json:"finishTime,omitempty"`
}

type ThirdPaymentWxPayCallbackResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateTradeStateReq struct {
	Sn             string `json:"sn"`
	TradeState     string `json:"tradeState"`
	TransactionId  string `json:"transactionId"`
	TradeType      string `json:"tradeType"`
	TradeStateDesc string `json:"tradeStateDesc"`
	PayStatus      int64  `json:"payStatus"`
	PayTime        int64  `json:"payTime"`
}

type UpdateTradeStateResp struct {
}
